### ISSUE TITLE
button font weight

### ISSUE THREAD

**Issue by rdela** [socketsupply/tonic-docs#18]
the [button](https://tonicframework.dev/examples.html#button) font-weight is heavy for my taste, disabling the:

```css
tonic-button button {
  font: 12px var(--tonic-subheader, 'Arial', sans-serif);
}
```

…rule looks better IMO
